# Knowledge Index — {{projectName}}

> Last updated: {{lastUpdated}} | {{sessionCount}} sessions | {{conceptCount}} concepts | {{gapCount}} gaps

---

## Active Concepts (referenced in last 30 days)

{{activeConcepts}}

## Stale Concepts (not referenced recently)

{{staleConcepts}}

## Knowledge Gaps (top {{topGapCount}})

{{topGaps}}

## Recent Sessions

{{recentSessions}}

---

*Generated by DKC. Run `/gaps` to see all knowledge gaps, `/learned` to see learning summary.*
